sequenceDiagram
    participant User
    participant KneeSpaApp as KneeSpa App
    participant Arduino
    participant Actuators

    User->>KneeSpaApp: Select Protocol
    KneeSpaApp->>Arduino: Reset Actuators
    Arduino->>Actuators: Reset Command
    Actuators->>Arduino: Status Update
    Arduino->>KneeSpaApp: Status Received
    
    User->>KneeSpaApp: Start Protocol
    
    KneeSpaApp->>Arduino: Set Flexion Angle
    Arduino->>Actuators: Position Command
    
    KneeSpaApp->>Arduino: Set Initial Pressure
    Arduino->>Actuators: Pressure Command
    
    Actuators->>Arduino: Status Update
    Arduino->>KneeSpaApp: Status Received
    
    KneeSpaApp->>Arduino: Gradual Pressure Incr.
    Arduino->>Actuators: Pressure Command
    
    KneeSpaApp->>Arduino: Optional: Set Lat Angle
    Arduino->>Actuators: Position Command
    
    KneeSpaApp->>Arduino: Optional: Enable Pulse
    Arduino->>Actuators: Jerk Command
    
    KneeSpaApp->>User: Wait for Protocol Duration
    
    KneeSpaApp->>Arduino: Protocol Complete
    Arduino->>Actuators: Reset Command
    
    KneeSpaApp->>User: Protocol Finished Message
