# tests/unit/test_conversions.py
"""Unit tests for KneeSpa distance/degree conversion helpers.

Covers ``KneeSpa.set_to_distance(inches, actuator, factor)`` and
``KneeSpa.set_to_c_distance(degrees)``. Both methods live on the 2400-line
``KneeSpa`` QMainWindow, so they are called UNBOUND against a lightweight stub
``self`` that only carries the attributes each method actually reads. This
avoids constructing the real Qt window.

FROZEN-CONVENTION POLICY: these tests assert CURRENT behavior only. The A-command
formula and the degree-interpolation arithmetic are pinned exactly as kneespa.py
implements them today; the tests are guards against accidental regression, not a
statement that the current numbers are "correct".
"""

import types
from unittest.mock import MagicMock

import pytest

from kneespa import KneeSpa
from config.config import Configuration


def make_config_with_defaults():
    """Build a Configuration populated with the default mark tables."""
    config = Configuration()
    config._set_default_c_marks()
    config._set_default_a_marks()
    config._set_default_b_marks()
    return config


def make_c_stub(config=None):
    """Lightweight stub carrying only what KneeSpa.set_to_c_distance reads.

    set_to_c_distance touches: loading_spinner (show/hide),
    disable/enable_actuator_controls, config.CMarks, arduino.send,
    I2CStatus, and I2Cstatus_event.clear().
    """
    if config is None:
        config = make_config_with_defaults()
    return types.SimpleNamespace(
        loading_spinner=MagicMock(),
        disable_actuator_controls=MagicMock(),
        enable_actuator_controls=MagicMock(),
        config=config,
        arduino=MagicMock(),
        I2CStatus=1,
        I2Cstatus_event=MagicMock(),
    )


def make_distance_stub():
    """Lightweight stub carrying only what KneeSpa.set_to_distance reads.

    set_to_distance touches: arduino.send, I2CStatus, I2Cstatus_event.clear(),
    and enable_actuator_controls().
    """
    return types.SimpleNamespace(
        arduino=MagicMock(),
        I2CStatus=1,
        I2Cstatus_event=MagicMock(),
        enable_actuator_controls=MagicMock(),
    )


def sent_command(stub):
    """Return the last command string passed to the stub's arduino.send."""
    return stub.arduino.send.call_args[0][0]


# Default CMarks reference values (regenerated by _set_default_c_marks):
#   angle = i*2.5 - 20, ratio = i/16, pos = round(500 + 1900*ratio) for i in 0..16
# -20.0 -> 500, -17.5 -> 619, -15.0 -> 738, 0.0 -> 1450, 17.5 -> 2281, 20.0 -> 2400


@pytest.mark.unit
class TestSetToDistance:
    """Tests for the axial A-command formatting (set_to_distance)."""

    def test_sends_a_command_with_actuator_and_inches(self):
        """Command is 'A<actuator><inches:.1f>' per the frozen format."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 3.0, "A", 1900)
        stub.arduino.send.assert_called_once_with("AA3.0")

    def test_inches_formatted_to_one_decimal(self):
        """Inches always render with exactly one decimal place."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 2, "A", 1900)
        assert sent_command(stub) == "AA2.0"

    def test_fractional_inches_preserved(self):
        """A fractional input keeps its one-decimal representation."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 1.5, "A", 1900)
        assert sent_command(stub) == "AA1.5"

    def test_zero_inches(self):
        """Zero inches is sent as the literal 'A<actuator>0.0'."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 0, "A", 1900)
        assert sent_command(stub) == "AA0.0"

    def test_actuator_letter_is_embedded(self):
        """The actuator identifier is placed between the 'A' prefix and value."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 4.0, "B", 1900)
        assert sent_command(stub) == "AB4.0"

    def test_factor_does_not_change_sent_command(self):
        """FROZEN: the internal 'position' uses factor, but the SENT command
        is driven only by inches/actuator. Two factors -> identical command."""
        stub_a = make_distance_stub()
        stub_b = make_distance_stub()
        KneeSpa.set_to_distance(stub_a, 2.0, "A", 1900)
        KneeSpa.set_to_distance(stub_b, 2.0, "A", 8)
        assert sent_command(stub_a) == sent_command(stub_b) == "AA2.0"

    def test_clears_i2c_status_and_event(self):
        """Side effects: I2CStatus reset to 0 and the status event cleared."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 1.0, "A", 1900)
        assert stub.I2CStatus == 0
        stub.I2Cstatus_event.clear.assert_called_once()

    def test_re_enables_actuator_controls(self):
        """Controls are re-enabled after the command is dispatched."""
        stub = make_distance_stub()
        KneeSpa.set_to_distance(stub, 1.0, "A", 1900)
        stub.enable_actuator_controls.assert_called_once()


@pytest.mark.unit
class TestSetToCDistanceExactMarks:
    """Exact-mark lookups in set_to_c_distance."""

    def test_zero_degrees_hits_exact_mark(self):
        """0.0 deg -> CMarks['0.0'] == 1450, sent as 'K1450'."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, 0.0)
        assert result is True
        stub.arduino.send.assert_called_with("K1450")

    def test_min_mark_lookup(self):
        """-20.0 deg -> CMarks['-20.0'] == 500, sent as 'K500'."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, -20.0)
        assert result is True
        stub.arduino.send.assert_called_with("K500")

    def test_max_mark_lookup(self):
        """20.0 deg -> CMarks['20.0'] == 2400, sent as 'K2400'."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, 20.0)
        assert result is True
        stub.arduino.send.assert_called_with("K2400")

    def test_positive_mark_lookup(self):
        """17.5 deg -> CMarks['17.5'] == 2281, sent as 'K2281'."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, 17.5)
        assert result is True
        stub.arduino.send.assert_called_with("K2281")

    def test_rounds_to_nearest_half_degree(self):
        """Input is rounded to nearest 0.5 deg; 0.1 -> 0.0 -> exact mark 1450."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, 0.1)
        assert result is True
        stub.arduino.send.assert_called_with("K1450")

    def test_accepts_string_degrees(self):
        """Degrees are coerced via float(); a numeric string works."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, "0.0")
        assert result is True
        stub.arduino.send.assert_called_with("K1450")


@pytest.mark.unit
class TestSetToCDistanceInterpolation:
    """Between-mark linear interpolation in set_to_c_distance."""

    def test_interpolates_between_marks(self):
        """-16.0 deg is not a mark; interpolate between -17.5(619) and -15.0(738).

        ratio = (-16.0 - (-17.5)) / (-15.0 - (-17.5)) = 1.5/2.5 = 0.6
        position = 619 + int((738 - 619) * 0.6) = 619 + int(71.4) = 619 + 71 = 690
        """
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, -16.0)
        assert result is True
        stub.arduino.send.assert_called_with("K690")

    def test_interpolation_uses_integer_truncation(self):
        """FROZEN: interpolation uses int() truncation of the delta, not rounding.

        14.0 deg falls between 12.5(2044) and 15.0(2162).
        ratio = (14.0 - 12.5) / (15.0 - 12.5) = 1.5/2.5 = 0.6
        position = 2044 + int((2162 - 2044) * 0.6) = 2044 + int(70.8) = 2044 + 70 = 2114
        """
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, 14.0)
        assert result is True
        stub.arduino.send.assert_called_with("K2114")

    def test_interpolated_command_has_k_prefix(self):
        """An interpolated command still carries the 'K' prefix."""
        stub = make_c_stub()
        KneeSpa.set_to_c_distance(stub, -16.0)
        call_arg = sent_command(stub)
        assert call_arg.startswith("K")
        assert int(call_arg[1:]) == 690


@pytest.mark.unit
class TestSetToCDistanceClamping:
    """Range-end clamping in set_to_c_distance (bounds are [-20.0, 20.0])."""

    def test_clamps_below_minimum(self):
        """Degrees below -20 clamp to -20.0 -> 'K500'."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, -25.0)
        assert result is True
        stub.arduino.send.assert_called_with("K500")

    def test_clamps_above_maximum(self):
        """Degrees above 20 clamp to 20.0 -> 'K2400'."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, 25.0)
        assert result is True
        stub.arduino.send.assert_called_with("K2400")

    def test_clamp_matches_exact_mark_at_boundary(self):
        """The clamped boundary value resolves through the exact-mark path."""
        stub_clamped = make_c_stub()
        stub_exact = make_c_stub()
        KneeSpa.set_to_c_distance(stub_clamped, 100.0)
        KneeSpa.set_to_c_distance(stub_exact, 20.0)
        assert sent_command(stub_clamped) == sent_command(stub_exact) == "K2400"


@pytest.mark.unit
class TestSetToCDistanceSideEffects:
    """Spinner / control / I2C side effects of set_to_c_distance."""

    def test_clears_i2c_status_and_event_on_success(self):
        stub = make_c_stub()
        KneeSpa.set_to_c_distance(stub, 0.0)
        assert stub.I2CStatus == 0
        stub.I2Cstatus_event.clear.assert_called_once()

    def test_toggles_loading_spinner(self):
        """Spinner shows on entry and hides before the successful return."""
        stub = make_c_stub()
        KneeSpa.set_to_c_distance(stub, 0.0)
        stub.loading_spinner.show.assert_called_once()
        stub.loading_spinner.hide.assert_called_once()

    def test_disables_then_enables_controls(self):
        stub = make_c_stub()
        KneeSpa.set_to_c_distance(stub, 0.0)
        stub.disable_actuator_controls.assert_called_once()
        stub.enable_actuator_controls.assert_called_once()

    def test_returns_false_and_hides_spinner_on_bad_input(self):
        """FROZEN: non-numeric degrees raise inside the try; the method swallows
        the error, hides the spinner, and returns False (no command sent)."""
        stub = make_c_stub()
        result = KneeSpa.set_to_c_distance(stub, "not-a-number")
        assert result is False
        stub.arduino.send.assert_not_called()
        stub.loading_spinner.hide.assert_called_once()
